export const analyzeJobMatchPrompt = `
Analyze one resume against one job description. Return exactly one JSON object with only these top-level keys: {"job": JobAnalysis, "match": MatchAnalysis}. Do not add top-level fields.

Use only supplied facts. Do not invent or rewrite resume content. Keep evidence and recommendations concise. A skill is matched only with resume evidence; identify missing and partial requirements honestly. Treat no relevant requirement as a neutral score of 100. Scores are 0-100. Status is derived by the application.

JobAnalysis fields: jobTitle, companyName, location, employmentType (string or null); experienceRequirements and educationRequirements (arrays of {requirement, importance: required|preferred|unclear}); requiredSkills and preferredSkills (arrays of {skill, category}); responsibilities, requiredQualifications, preferredQualifications, keywords, softSkills, toolsAndTechnologies, certifications (string arrays); summary (a short string summarizing the job). Include only the most relevant, source-supported items. Limits: 4 experience requirements, 3 education requirements, 5 required skills, 3 preferred skills, 4 responsibilities, 3 required qualifications, 2 preferred qualifications, 10 keywords, 4 soft skills, 5 tools, 3 certifications. Keep each list value concise (preferably under 8 words); summary under 18 words.

MatchAnalysis fields: overallScore; summary; categoryScores {skills, experience, keywords, education, responsibilities, qualifications}; matchedSkills [{skill,resumeEvidence,jobRequirement}]; missingSkills [{skill,importance:high|medium|low,reason}]; partialMatches [{requirement,explanation,resumeEvidence}]; matchedKeywords and missingKeywords (string arrays); responsibilityMatches [{responsibility,matched,explanation,resumeEvidence}]; strengths [{title,explanation}]; gaps [{category,title,explanation,importance:high|medium|low}]; recommendations [{title,explanation}]. For every responsibilityMatches item, matched MUST be a JSON boolean: use true or false without quotes. NEVER use "true" or "false" strings, Yes/No, or 1/0 for matched. Example: {"matched":true}. Use empty arrays when appropriate. Limits: 5 matched and 5 missing skills, 3 partial matches, 8 matched and 8 missing keywords, 4 responsibility matches, 2 strengths, 3 gaps, and 3 recommendations. Keep all text values brief (one short phrase or sentence, preferably under 10 words); do not repeat the full requirement when a short label is sufficient. Do not return a status field; the application derives it from overallScore. Never suggest claiming unsupported experience or skills.

Return every field, concise JSON values only. No markdown or explanation outside the JSON object.
`;
